paths:
  /v1/daas/contract/{id}/devices:
    get:
      tags: [DaaS/Devices]
      summary: Get Devices linked to a Contract
      description: Retrieve the list of DaaS devices associated with a specific contract ID.
      parameters:
        - name: id
          in: path
          description: Unique ID of the DaaS contract
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: List of devices retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DaasDevice"
        "404":
          description: Contract not found
        "500":
          description: Internal server error
    put:
      tags: [DaaS/Contracts]
      summary: Add Devices to a Contract
      description: Associate one or more devices to a specific DaaS contract. Devices can be created with services and accessories.
      parameters:
        - name: id
          in: path
          description: Unique ID of the DaaS contract
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddDevicesToContractRequest"
      responses:
        "200":
          description: Devices added to contract successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DaasDevice"
        "400":
          description: Bad request - invalid input data
        "404":
          description: Contract not found
        "500":
          description: Internal server error

  /v1/daas/device/{id}:
    get:
      tags: [DaaS/Devices]
      summary: Get a DaaS Device by ID Device
      description: Retrieve detailed information for a specific DaaS device.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Device retrieved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DaasDevice"
        "404":
          description: Device not found
        "500":
          description: Internal server error
    delete:
      tags: [DaaS/Devices]
      summary: Delete a DaaS Device
      description: Delete a specific DaaS device and remove its association from the contract.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Unique ID of the DaaS device to delete
      responses:
        "200":
          description: Device deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  deviceId:
                    type: integer
        "404":
          description: Device not found
        "500":
          description: Internal server error

  /v1/daas/device/{id}/element:
    put:
      tags: [DaaS/Devices]
      summary: Add or update elements (services/accessories) to a Device
      description: Associate or remove services and accessories from a specific device.
      parameters:
        - name: id
          in: path
          description: Unique ID of the DaaS device
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceElementRequest"
      responses:
        "200":
          description: Device elements updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DaasDevice"
        "400":
          description: Bad request - invalid input data
        "404":
          description: Device not found
        "500":
          description: Internal server error
